! $Id: vaba_param.inc 1048 2012-08-23 06:26:15Z boman $
!> \file vaba_param.inc
!> Abaqus include file for VUMAT subroutines
!!
!! This file is \b NOT compiled by Abaqus! \n
!! This modified version is included by the python interface

implicit none

!implicit real(8) (a-h,o-z)
!parameter (j_sys_Dimension = 2)
!parameter( n_vec_Length = 544  )
!parameter( maxblk = n_vec_Length  )
!parameter(i_ipm_sta = -6)
!character*5 j_ipm_Error
!parameter(j_ipm_Error = "Error")
!parameter(j_ipm_Aborted = 20)
!parameter(r_MaxVal = 1.d+30)
